// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1734306714);
user_pref("app.update.lastUpdateTime.background-update-timer", 1734306714);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1734306714);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1733930811);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240801134912");
user_pref("browser.startup.homepage_override.mstone", "115.14.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20241126084514");
user_pref("extensions.lastAppVersion", "7.0.10");
user_pref("extensions.lastPlatformVersion", "115.14.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"better-bibtex@iris-advies.com\":\"9a01f21f-6177-4862-8cdc-08825c150696\"}");
user_pref("extensions.zotero.automaticSnapshots", false);
user_pref("extensions.zotero.automaticTags", false);
user_pref("extensions.zotero.dataDir", "/home/tai/OneDrive_Student/Zotero Storage");
user_pref("extensions.zotero.export.lastTranslator", "ca65189f-8815-4afe-8c8b-8c7c15f0edca");
user_pref("extensions.zotero.export.translatorSettings", "{\"exportNotes\":false,\"exportFileData\":false,\"useJournalAbbreviation\":false,\"keepUpdated\":true,\"worker\":true,\"includeAnnotations\":false}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "C1");
user_pref("extensions.zotero.layout", "stacked");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"180\"},\"zotero-layout-switcher\":{\"orient\":\"vertical\"},\"zotero-items-splitter\":{\"orient\":\"vertical\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"},\"zotero-collections-pane\":{\"width\":\"200\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.better-bibtex-iris-advies-com-betterbibtex-section-citationkey.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.reader.contentDarkMode", false);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C1\",\"sessionID\":\"5rHmPLEZ\"}]");
user_pref("extensions.zotero.sync.server.username", "witherstai@gmail.com");
user_pref("extensions.zotero.tempStackedMode", true);
user_pref("extensions.zotero.translators.better-bibtex.DOIandURL", "doi");
user_pref("extensions.zotero.translators.better-bibtex.autoExport.%2Fhome%2Ftai%2FOneDrive_Student%2FMScThesis%2FQSTAR%2ebib", "{\"path\":\"/home/tai/OneDrive_Student/MScThesis/QSTAR.bib\",\"translatorID\":\"ca65189f-8815-4afe-8c8b-8c7c15f0edca\",\"type\":\"collection\",\"id\":1,\"status\":\"done\",\"error\":\"\",\"recursive\":false,\"updated\":1733943234574,\"enabled\":true,\"bibtexURL\":\"url\",\"DOIandURL\":\"doi\",\"exportNotes\":false,\"useJournalAbbreviation\":false}");
user_pref("extensions.zotero.translators.better-bibtex.automaticTags", false);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/home/tai/.local/state/nix/profile/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.translators.better-bibtex.skipFields", "urldate,keywords,annotation,shorttitle,abstract,langid,file,archiveprefix");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotero.warnOnUnsafeDataDir", false);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.1.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1734306777);
user_pref("intl.accept_languages", "en-US, en");
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1734306777466");
user_pref("security.sandbox.content.tempDirSuffix", "27956067-6595-4f66-8a88-77e550aac775");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1733931844);
