# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'space']
quit = ['q', 'esc']
# movement
list_up = ['up', 'k']
list_down = ['down', 'j']
# file panel control
create_new_file_panel = ['n', '']
close_file_panel = ['w', '']
next_file_panel = ['tab', '']
previous_file_panel = ['shift+tab', '']
toggle_file_preview_panel = ['f', '']
# change focus
focus_on_process_bar = ['P', '']
focus_on_sidebar = ['S', '']
focus_on_metadata = ['M', '']
# create file/directory and rename
file_panel_item_create = ['c', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['ctrl+c', 'y']
cut_items = ['ctrl+x', 'x']
paste_items = ['ctrl+v', 'p']
delete_items = ['ctrl+d', 'delete', 'd']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# other
pinned_directory = ['ctrl+p', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']

# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']

# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', "backspace"]
search_bar = ['/', 'ctrl+f']

# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['A', '']